name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: |
        cd hamalba/src
        dotnet restore
    - name: Build
      run: |
        cd hamalba/src
        dotnet build --no-restore
    - name: Test
      run: |
        cd hamalba/src
        dotnet test --no-build --verbosity normal